### PR TITLE
Port to Python3

### PR DESCRIPTION
**Pull request by srevinsaju**

### CODE REVIEW

**Comment by Aniket21mathur** [comment]
@srevinsaju also update the version of sugargame in `__init__.py`

**Comment by srevinsaju** [comment]
@Aniket21mathur done on https://github.com/sugarlabs/pointillism-activity/pull/27/commits/94ea96d65733ca085b181e957cc02ea6e15e2a5b

**Comment by quozl** [comment]
https://github.com/sugarlabs/pointillism-activity/pull/27/commits/ce1c93ef317ef9fdf82f53fa748209910047b24d is different to the fix we used in Sugargame, is there a reason we can't use what is Sugargame now?

**Comment by srevinsaju** [comment]
https://github.com/sugarlabs/pointillism-activity/commit/ce1c93ef317ef9fdf82f53fa748209910047b24d is not completely python3 ported. I didn't want to use that, I have ported this. When I went through ci's it gave a lot of errors, and I was lazy to fix them. As this had lesser errors, I ported it to Python3. If i get time, I will fix those too

**Comment by quozl** [comment]
Thanks.  I tested your version, and with same code from Sugargame, but couldn't get the activity to work.  Display remained unchanged.  Also the same thing with _master_ branch, 5f621fa2a610f1d877b4481d9c32ee1f525eec5c.  This was with Ubuntu 18.04 on a laptop with a camera.  So I've raised https://github.com/sugarlabs/pointillism-activity/issues/28.

I won't merge a Port to Python 3 until this problem can be fixed; this is covered in our [Python 3 Porting Guide](https://github.com/sugarlabs/sugar-docs/blob/master/src/python-porting-guide.md#how-to-port-an-activity-to-python-3) where it says _Quiesce the activity source by making sure the activity works properly before porting_.

**Comment by srevinsaju** [comment]
@quozl, shall I use the fixed sugarcane, does it relate to that?

**Comment by quozl** [comment]
As I already tested with the same code from Sugargame, it can't be that.

**Comment by srevinsaju** [comment]
@quozl any errors?

**Comment by srevinsaju** [comment]
If it doesn't start at all saying about Gdk Errors and segmentation faults, you might beusing Wayland.
Fix that by `export GDK_BACKEND=x11`

**Comment by srevinsaju** [comment]
@quozl 
Screenshot from 2019-12-10 00-37-24
Screenshot from 2019-12-10 00-37-37
Screenshot from 2019-12-10 00-37-46
A working image of pointillism, ported to python3

**Comment by quozl** [comment]
@srevinsaju, I've added a couple of commits for you to review.  Tested on Ubuntu 18.04 with Sugar 0.116 on a One Education Infinity laptop; native, no VM.

**Comment by srevinsaju** [comment]
@quozl Can we separate out sugargame, out so that it can be a separate repo which clones sugargame once its initialized for the first time. We can implement this with gitpython, so that only one piece of sugargame works

**Comment by srevinsaju** [comment]
@quozl , tested, works thanks

**Comment by quozl** [comment]
Thanks for asking.

We dabbled in submodules, but found it unworkable.

See
https://github.com/sugarlabs/browse-activity/commit/b8edc6415b7554c5d4dcaeb6db631c77465f683c
for explanation.

But mostly, the reason why we can't just update Sugargame
automatically is that Sugargame changes API slightly with each new
version, and so an automatic update would induce regressions.

A more reliable process is to read the commits to Sugargame in diff
format and then understand what to change in the activity.

This does require that people understand how to read commits in diff
format, which GitHub shows in the usual red and green highlight.

**Comment by quozl** [comment]
I've tested again and am ready to merge.

**Pull request merged**
